# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ActiveSoftware.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ActiveSoftware(object):
    def setupUi(self, ActiveSoftware):
        ActiveSoftware.setObjectName("ActiveSoftware")
        ActiveSoftware.resize(606, 302)
        ActiveSoftware.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.centralwidget = QtWidgets.QWidget(ActiveSoftware)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 30, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Square Dot-Matrix")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtonActiveSoftware = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonActiveSoftware.setGeometry(QtCore.QRect(160, 140, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(14)
        self.pushButtonActiveSoftware.setFont(font)
        self.pushButtonActiveSoftware.setObjectName("pushButtonActiveSoftware")
        self.MACHINECODE = QtWidgets.QLabel(self.centralwidget)
        self.MACHINECODE.setGeometry(QtCore.QRect(50, 70, 511, 51))
        font = QtGui.QFont()
        font.setFamily("Square Dot-Matrix")
        font.setPointSize(20)
        font.setUnderline(True)
        self.MACHINECODE.setFont(font)
        self.MACHINECODE.setMouseTracking(False)
        self.MACHINECODE.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.MACHINECODE.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MACHINECODE.setAutoFillBackground(True)
        self.MACHINECODE.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.MACHINECODE.setObjectName("MACHINECODE")
        self.labelTimeRemain = QtWidgets.QLabel(self.centralwidget)
        self.labelTimeRemain.setGeometry(QtCore.QRect(200, 210, 221, 31))
        self.labelTimeRemain.setText("")
        self.labelTimeRemain.setObjectName("labelTimeRemain")
        ActiveSoftware.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ActiveSoftware)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 606, 23))
        self.menubar.setObjectName("menubar")
        ActiveSoftware.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ActiveSoftware)
        self.statusbar.setObjectName("statusbar")
        ActiveSoftware.setStatusBar(self.statusbar)

        self.retranslateUi(ActiveSoftware)
        self.pushButtonActiveSoftware.clicked.connect(ActiveSoftware.ActiveSoftware) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ActiveSoftware)

    def retranslateUi(self, ActiveSoftware):
        _translate = QtCore.QCoreApplication.translate
        ActiveSoftware.setWindowTitle(_translate("ActiveSoftware", "ActiveSoftware"))
        self.label.setText(_translate("ActiveSoftware", "Your MachineCode Is"))
        self.pushButtonActiveSoftware.setText(_translate("ActiveSoftware", "ACTIVE"))
        self.MACHINECODE.setText(_translate("ActiveSoftware", "FBFE6EB8EED318D24A1FDEA71C7104CA"))
