# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ComSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComSetting(object):
    def setupUi(self, ComSetting):
        ComSetting.setObjectName("ComSetting")
        ComSetting.resize(565, 314)
        self.buttonBox = QtWidgets.QDialogButtonBox(ComSetting)
        self.buttonBox.setGeometry(QtCore.QRect(190, 230, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBoxCOM = QtWidgets.QComboBox(ComSetting)
        self.comboBoxCOM.setGeometry(QtCore.QRect(80, 130, 131, 31))
        self.comboBoxCOM.setObjectName("comboBoxCOM")
        self.comboBoxBaudrate = QtWidgets.QComboBox(ComSetting)
        self.comboBoxBaudrate.setGeometry(QtCore.QRect(310, 130, 131, 31))
        self.comboBoxBaudrate.setObjectName("comboBoxBaudrate")
        self.comboBoxBaudrate.addItem("")
        self.comboBoxBaudrate.addItem("")
        self.comboBoxBaudrate.addItem("")
        self.comboBoxBaudrate.addItem("")
        self.label = QtWidgets.QLabel(ComSetting)
        self.label.setGeometry(QtCore.QRect(80, 90, 121, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ComSetting)
        self.label_2.setGeometry(QtCore.QRect(310, 90, 121, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(ComSetting)
        self.buttonBox.accepted.connect(ComSetting.setCom) # type: ignore
        self.buttonBox.rejected.connect(ComSetting.reject) # type: ignore
        self.comboBoxCOM.currentTextChanged['QString'].connect(ComSetting.refreshCom) # type: ignore
        self.comboBoxBaudrate.currentTextChanged['QString'].connect(ComSetting.setBaudrate) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ComSetting)

    def retranslateUi(self, ComSetting):
        _translate = QtCore.QCoreApplication.translate
        ComSetting.setWindowTitle(_translate("ComSetting", "Dialog"))
        self.comboBoxBaudrate.setItemText(0, _translate("ComSetting", "4800"))
        self.comboBoxBaudrate.setItemText(1, _translate("ComSetting", "9600"))
        self.comboBoxBaudrate.setItemText(2, _translate("ComSetting", "11400"))
        self.comboBoxBaudrate.setItemText(3, _translate("ComSetting", "115200"))
        self.label.setText(_translate("ComSetting", "COM"))
        self.label_2.setText(_translate("ComSetting", "BAUDRATE"))
