# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Welcome(object):
    def setupUi(self, Welcome):
        Welcome.setObjectName("Welcome")
        Welcome.resize(903, 468)
        Welcome.setMinimumSize(QtCore.QSize(0, 0))
        Welcome.setMaximumSize(QtCore.QSize(167775, 167775))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        Welcome.setFont(font)
        Welcome.setAutoFillBackground(True)
        self.label = QtWidgets.QLabel(Welcome)
        self.label.setGeometry(QtCore.QRect(130, 70, 681, 261))
        self.label.setMaximumSize(QtCore.QSize(1677216, 16777215))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/pic/LOADPAGE.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.progressBarLoad = QtWidgets.QProgressBar(Welcome)
        self.progressBarLoad.setGeometry(QtCore.QRect(130, 310, 681, 20))
        self.progressBarLoad.setProperty("value", 61)
        self.progressBarLoad.setTextVisible(False)
        self.progressBarLoad.setInvertedAppearance(False)
        self.progressBarLoad.setObjectName("progressBarLoad")
        self.labelinfo = QtWidgets.QLabel(Welcome)
        self.labelinfo.setGeometry(QtCore.QRect(520, 290, 291, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setItalic(False)
        self.labelinfo.setFont(font)
        self.labelinfo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelinfo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelinfo.setObjectName("labelinfo")

        self.retranslateUi(Welcome)
        QtCore.QMetaObject.connectSlotsByName(Welcome)

    def retranslateUi(self, Welcome):
        _translate = QtCore.QCoreApplication.translate
        Welcome.setWindowTitle(_translate("Welcome", "Welcome"))
        self.labelinfo.setText(_translate("Welcome", "System Initializing . . ."))
import load_rc
