# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AboutSystem.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import about_rc

class Ui_AboutSystem(object):
    def setupUi(self, AboutSystem):
        AboutSystem.setObjectName("AboutSystem")
        AboutSystem.resize(859, 476)
        self.centralwidget = QtWidgets.QWidget(AboutSystem)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 391, 261))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/pic/haidongqing.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(410, 40, 421, 271))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 350, 81, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/pic/qt.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 350, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Square Dot-Matrix")
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(620, 350, 111, 71))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/pic/python.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        AboutSystem.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AboutSystem)
        self.statusbar.setObjectName("statusbar")
        AboutSystem.setStatusBar(self.statusbar)

        self.retranslateUi(AboutSystem)
        QtCore.QMetaObject.connectSlotsByName(AboutSystem)

    def retranslateUi(self, AboutSystem):
        _translate = QtCore.QCoreApplication.translate
        AboutSystem.setWindowTitle(_translate("AboutSystem", "About Gyrflacon System"))
        self.textBrowser.setHtml(_translate("AboutSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'Segoe UI\',\'Noto Sans\',\'Helvetica\',\'Arial\',\'sans-serif\',\'Apple Color Emoji\',\'Segoe UI Emoji\'; font-size:16px; color:#1f2328; background-color:#ffffff;\">Gyrfalcon high-speed wired high-power gas sensing array series.Data acquisition for artificial olfactory systems implemented in artificial neural networks and traditional machine learning</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'Segoe UI\',\'Noto Sans\',\'Helvetica\',\'Arial\',\'sans-serif\',\'Apple Color Emoji\',\'Segoe UI Emoji\'; font-size:16px; font-style:italic; color:#1f2328;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'Segoe UI\',\'Noto Sans\',\'Helvetica\',\'Arial\',\'sans-serif\',\'Apple Color Emoji\',\'Segoe UI Emoji\'; font-size:16px; font-style:italic; color:#1f2328; background-color:#ffffff;\">Gyrfalcon(Haidongqing) is a large bird of prey in the family of Falconidae. It is known for its speed and hunting ability. Gyrfalcon(Haidongqing) is a popular bird in falconry and is often used by falconers to hunt smaller birds and mammals.In the past, Gyrfalcon(Haidongqing) was also known as the &quot;Divine Eagle&quot; and was considered a symbol of courage and power.</span></p></body></html>"))
        self.label_3.setText(_translate("AboutSystem", "Powered by "))

