#ifndef  BOARD_PINMAP_H
#define  BOARD_PINMAP_H

#include "nrf_gpio.h"

#define BOARD_SPI_SCK_PIN	NRF_GPIO_PIN_MAP(0,23)
#define BOARD_SPI_MISO_PIN	NRF_GPIO_PIN_MAP(0,19)
#define BOARD_SPI_MOSI_PIN	NRF_GPIO_PIN_MAP(0,21)

#define BOARD_AD7124_CS_PIN NRF_GPIO_PIN_MAP(0,9)
#define BOARD_FLASH_CS_PIN	NRF_GPIO_PIN_MAP(0,12)

#define BOARD_IIC_SDA_PIN	NRF_GPIO_PIN_MAP(0,2)
#define BOARD_IIC_SCL_PIN	NRF_GPIO_PIN_MAP(0,31)

#define BOARD_UART_TX_PIN	NRF_GPIO_PIN_MAP(1,03)
#define BOARD_UART_RX_PIN	NRF_GPIO_PIN_MAP(1,10)
#define BOARD_UART_BAUDRATE 115200

#define BOARD_LED_DIR_PORT	0
#define BOARD_LED_DIR_PIN	7

#endif // 
